/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: bc3d8ae7e4ba3e24c7d7626bed49bb82)
interface __BaseEnv_Env {
	DB: D1Database;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
